In [1]:
import pandas as pd 

df = pd.read_csv('The_Cancer_data_1500_V2.csv')
df

,Age,Gender,BMI,Smoking,GeneticRisk,PhysicalActivity,AlcoholIntake,CancerHistory,Diagnosis
0,58,1,16.085313,0,1,8.146251,4.148219,1,1
1,71,0,30.828784,0,1,9.361630,3.519683,0,0
2,48,1,38.785084,0,2,5.135179,4.728368,0,1
3,34,0,30.040296,0,0,9.502792,2.044636,0,0
4,62,1,35.479721,0,0,5.356890,3.309849,0,1
...,...,...,...,...,...,...,...,...,...
1495,62,1,25.090025,0,0,9.892167,1.284158,0,1
1496,31,0,33.447125,0,1,1.668297,2.280636,1,1
1497,63,1,32.613861,1,1,0.466848,0.150101,0,1
1498,55,0,25.568216,0,0,7.795317,1.986138,1,1
1499,67,1,23.663104,0,0,2.525860,2.856600,1,0

In [3]:
label = df['Diagnosis']
features = df.drop(columns=['Diagnosis'])
print(label)
features

0       1
1       0
2       1
3       0
4       1
       ..
1495    1
1496    1
1497    1
1498    1
1499    0
Name: Diagnosis, Length: 1500, dtype: int64

,Age,Gender,BMI,Smoking,GeneticRisk,PhysicalActivity,AlcoholIntake,CancerHistory
0,58,1,16.085313,0,1,8.146251,4.148219,1
1,71,0,30.828784,0,1,9.361630,3.519683,0
2,48,1,38.785084,0,2,5.135179,4.728368,0
3,34,0,30.040296,0,0,9.502792,2.044636,0
4,62,1,35.479721,0,0,5.356890,3.309849,0
...,...,...,...,...,...,...,...,...
1495,62,1,25.090025,0,0,9.892167,1.284158,0
1496,31,0,33.447125,0,1,1.668297,2.280636,1
1497,63,1,32.613861,1,1,0.466848,0.150101,0
1498,55,0,25.568216,0,0,7.795317,1.986138,1
1499,67,1,23.663104,0,0,2.525860,2.856600,1

In [4]:
from sklearn.model_selection import train_test_split

traindata, testdata, train_labels, test_labels = train_test_split(features, 
                                                                  label,
                                                                  stratify=label,
                                                                  test_size=0.2,
                                                                  random_state=42)

In [24]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

model = gnb.fit(traindata, train_labels)

In [6]:
prediction = gnb.predict(testdata)
prediction

array([0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0])

In [7]:
from sklearn.metrics import accuracy_score

acc = accuracy_score(test_labels, prediction)
print(f'Model accurate in {acc*100} %')

Model accurate in 83.0 %

Experimenting with other naive bayeses

In [28]:
from sklearn.naive_bayes import BernoulliNB, CategoricalNB, ComplementNB, MultinomialNB

bnb = BernoulliNB()
catnb = CategoricalNB()
comnb = ComplementNB()
mnb = MultinomialNB()

gaus_model = gnb.fit(traindata, train_labels)
bernoulli_model = bnb.fit(traindata, train_labels)
categorical_model = catnb.fit(traindata, train_labels)
complement_model = comnb.fit(traindata, train_labels)
multinomial_model = mnb.fit(traindata, train_labels)

gauss_prediction = gaus_model.predict(testdata)
# print(gauss_prediction)
# model_list = [bernoulli_model, categorical_model, complement_model, multinomual_model]
bernoulli_prediction = bernoulli_model.predict(testdata)
categorical_prediction = categorical_model.predict(testdata)
complement_prediction = complement_model.predict(testdata)
multinomial_prediction = multinomial_model.predict(testdata) 

predictions_list = [gauss_prediction, bernoulli_prediction, categorical_prediction, complement_prediction, multinomial_prediction]
prediction_dict = {
    'Gauss': gauss_prediction,
    'Bernoulli': bernoulli_prediction,
    'Categorical': categorical_prediction,
    'Complement': complement_prediction,
    'Multinomial': multinomial_prediction
}

# test_acc = accuracy_score(test_labels, gauss_prediction)
# print(test_acc)
for name, prediction in prediction_dict.items():
    # print(name)
    acc = accuracy_score(test_labels, prediction)
    print(f'Accuracy for {name} is {acc*100}%')

Accuracy for Gauss is 83.0%
Accuracy for Bernoulli is 75.0%
Accuracy for Categorical is 91.33333333333333%
Accuracy for Complement is 74.66666666666667%
Accuracy for Multinomial is 76.33333333333333%